# Generated by Django 4.1.7 on 2023-03-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('correct', models.CharField(max_length=100)),
                ('wrong', models.CharField(max_length=200)),
            ],
        ),
    ]
